---
apiVersion: v1
kind: Service
metadata:
  name: packmind-api
  labels:
    component: app
  {{- range $key, $value := .Values.services.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    component: front
  {{- range $key, $value := .Values.services.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: front
  ports:
    - name: http
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: packmind-detection
  labels:
    component: detection
  {{- range $key, $value := .Values.services.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: detection
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: packmind-aiagent
  labels:
    component: aiagent
  {{- range $key, $value := .Values.services.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: aiagent
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: packmind-redis
  labels:
    component: redis
  {{- range $key, $value := .Values.services.labels }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
{{ if .Values.app.databaseEmbedded.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    component: mongodb
  {{- range $key, $value := .Values.services.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := .Values.services.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  selector:
    component: mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
{{ end }}
